### ISSUE TITLE
Meldii Update

### ISSUE THREAD

**Issue by zSleepwalker** [GoomiChan/Meldii#14]
When not running Meldii as administrator, the program crash at the update of Meldii.
If you run as Administrator, it says it's updating but it never does the update.

**Comment by zSleepwalker** [comment]
OS: Windows 8.1
Update with the error message:
http://imgur.com/T3raDvF

"Åtkomst till sökvägen" = "Path Acccess"
"vid" = "at"

**Comment by GoomiiV2** [comment]
Should be fixed, also i miss typed 15 in the commit instead of 14 for closing this :<
