### ISSUE TITLE
One-click install

### ISSUE THREAD

**Issue by theunkn0wn1** [GoomiChan/Meldii#27]
When attempting to use the one-click install feature of Meldii, which was also a feature of the old Melder, the addon/mod is successfully added to the Library however is neither installed nor does the GUI come up. 

Issue:[1]Addons/mods will not automaticially install via one-click
          [2]The GUI for this application does not come up after triggering one-click
Can you please address both of my concerns as noted above?
# 

tested against release version 1.7.5.0

**Comment by GoomiiV2** [comment]
[1] They are not meant to, the one click installs are meant to download and add that addon to your addon library. From there you can then decide to install it into the game. This is the same way Melder worked.

[2] The installs where intended to be silent and that an already running version of Meldii would detect the freshly added addon and the UI would update to reflect that.
I had planed to add an option that would show the main UI after a one click install if an existing Meldii instance wasn't running, I never got around to it as it is quite a low priority quality of life thing.

# **Also I would have addressed both of your concerns with out the bolded text <3**

**Comment by theunkn0wn1** [comment]
Sorry.. the bold was unintentional.. Forgot to double-check my formatting :/

When I attempted to use one-click with Meldii open, both instances crashed thus I inferred Meldii was not supposed to be running at the time of one-click hence issue [2] was born. 

[Meldii Errors make Arkii sad.txt](https://github.com/GoomiChan/Meldii/files/171285/Meldii.Errors.make.Arkii.sad.txt)

**Comment by GoomiiV2** [comment]
Ah thats ok then, no hard feelings :>

It crashing like that is definitely a bug, I'll look into it and hopefully have a fix out soon.

**Comment by GoomiiV2** [comment]
Could you try and replace your current Meldii with this and see if it fixes the crashing?
https://github.com/GoomiChan/Meldii/releases/tag/untagged-2a5c4552076b22cb0431

**Comment by theunkn0wn1** [comment]
link returns 404
if you push the code to a dedicated branch I can compile it my end and test it

**Comment by GoomiiV2** [comment]
The latest commit has it.

**Comment by theunkn0wn1** [comment]
OK, built against 03e413e5 and Meldii does not crash when One-click is triggered and one of its windows was still open just prior to that event. Consider this issue resolved. Thanks
