### ISSUE TITLE
Addon library location redirect

### ISSUE THREAD

**Issue by theunkn0wn1** [GoomiChan/Meldii#28]
I have a User setup as described below:
I have a root admin account `x`
I am logged in as a standard user `y`

I run Meldii as user `y` and grant it via UAC the admin privileges from `x` as requested.
When using the UI button on Meldii's main interface to open the library location the program incorrectly calls to `C:\users\y\Appdata\Local\Melder\addons\` even though its library is actually located in  `C:\users\x\Appdata\Local\Melder\addons\` and thus the below occurs.

![image](https://cloud.githubusercontent.com/assets/3110986/13732469/cae69390-e940-11e5-8315-d71ffe7b44e0.png)
# 

Testing against 3b19cdb27e45bbc8aa69e127934c1b6c61646530

**Comment by GoomiiV2** [comment]
That is very odd, that button uses what ever path is set in the "Addon Library Location" setting. :/

**Comment by theunkn0wn1** [comment]
Yeah.. I even tried hard-coding the function call in `MainWindow.xaml.cs` at line 187 to the correct path and rebuilding.. still called to the incorrect address :/ 

Also: I verified that the var `MeldiiSettings.Self.AddonLibaryPath` points to the correct location

**Comment by eXpl0it3r** [comment]
Once you grant UAC with x aren't you start acting as x, thus the user directory is x and not y?

**Comment by theunkn0wn1** [comment]
Yes. therein lies the problem. When attempting to open the library path via the UI button the program calls to the wrong directory, that of user `y`'s path and not than user`x`'s
I have cloned this repo and built it in my dev env and, when looking at the vars involved discover that `MeldiiSettings.Self.AddonLibaryPath`, the var that holds the path _in question_, **correctly points** to the path of user `x`
![image](https://cloud.githubusercontent.com/assets/3110986/13737709/9dfb259e-e97c-11e5-878a-6940c8063172.png)

yet, when the line that is highlighted in red (because break point) is executed, the result is
![image](https://cloud.githubusercontent.com/assets/3110986/13737746/ebb4716e-e97c-11e5-896e-34d17e2b014f.png)

please note that I have stripped the actual User Names and replaced them with hypothetical names x and y as described in my OP.

**Comment by GoomiiV2** [comment]
Ok it seems windows will "correct" the path automatically if explorer is not launched as an admin, commit 03e413e should now launch it with admin privileges so as long as your user account has permissions to access that folder it should work as expected.

If you could test it out and let me know if this fixes it for you that would be great :>

**Comment by theunkn0wn1** [comment]
~~Built c2fa741a and it goes to the right path now but now throws an "Access is denied" error...~~
Right.. my standard user cannot access that folder.... That is what you mean right when you state 

> so as long as your user account has permissions to access that folder it should work as expected.

Right?
![image](https://cloud.githubusercontent.com/assets/3110986/13767769/8b455c6c-ea2b-11e5-846e-5a998cee3ba1.png)

**Comment by GoomiiV2** [comment]
Yea, once I give my account access rights it works as expected now.

**Comment by theunkn0wn1** [comment]
OK. this particular issue can now be considered resolved. Thanks for the assistance!
